<a href="https://colab.research.google.com/github/Jessicaagnesiat/product-data-cleaning-missing-duplicates/blob/main/Mini_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# Mengimport library pandas untuk membaca dataset
import pandas as pd

# membaca dataset csv menggunakan syntax pd.read_csv()
df = pd.read_csv('/content/products_all_brands.csv')

In [10]:
df

,brand_name,product_name,product_id,beauty_point_earned,price_range,price_by_combinations,url,active_date,default_category,categories,rating_types_str,average_rating,total_reviews,average_rating_by_types,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
0,796_3ce,MULTI EYE COLOR PALETTE,97802,130,Rp 555.000 - Rp 687.000,NaN,https://www.sociolla.com/eyeshadow/69460-phan-...,2022-10-03T03:30:06.681Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.920000,5,"""star_long_wear"": 5; ""star_packaging"": 4.8; ""s...",5,0,0,5,717
1,796_3ce,VELVET LIP TINT,97810,50,Rp 264.000,NaN,https://www.sociolla.com/lip-cream/69468-son-k...,2022-10-03T03:02:40.340Z,Lip Cream,Makeup; Lips; Lip Cream,is_star_long_wear;is_star_packaging;is_star_pi...,4.576190,42,"""star_long_wear"": 4.309523809523809; ""star_pac...",42,10,2,30,682
2,796_3ce,LIP COLOR,97822,60,Rp 317.000,NaN,https://www.sociolla.com/lip-matte/69480-son-t...,2023-05-30T09:49:15.158Z,Lipstick,Makeup; Lips; Lipstick,is_star_long_wear;is_star_packaging;is_star_pi...,0.000000,0,NaN,0,0,0,0,173
3,796_3ce,MINI MULTI EYE COLOR PALETTE,97833,80,Rp 423.000,NaN,https://www.sociolla.com/eyeshadow/69491-phan-...,2022-10-03T03:27:01.334Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.883333,6,"""star_long_wear"": 4.916666666666667; ""star_pac...",12,1,0,11,257
4,796_3ce,FACE BLUSH,97801,60,Rp 300.000,NaN,https://www.sociolla.com/blush/69459-phan-ma-h...,2022-10-03T03:22:26.610Z,Blush,Makeup; Face; Blush,is_star_long_wear;is_star_packaging;is_star_pi...,4.858824,13,"""star_long_wear"": 4.9411764705882355; ""star_pa...",17,2,0,15,387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7631,273_yves-rocher,Ambre Noir Eau De Toilette,2158,130,Rp 659.000,NaN,https://sociolla.com/fragrance/8088-ambre-noir...,NaN,Eau De Toilette,Shop By Departments; Home; UOBMon,is_star_long_wear;is_star_packaging;is_star_va...,4.476190,7,"""star_long_wear"": 4.285714285714286; ""star_pac...",6,1,2,4,355
7632,273_yves-rocher,Soin Stimulating Conditioner,64174,30,Rp 199.000,NaN,https://vn.sociolla.com/d-u-x/17239-soin-stimu...,NaN,Conditioner,Hair Care; Shampoo; Conditioner,is_star_effectiveness;is_star_packaging;is_sta...,4.638889,9,"""star_effectiveness"": 4.444444444444445; ""star...",7,1,2,6,122
7633,273_yves-rocher,Repair Hair Mask,36357,50,Rp 289.000,NaN,https://www.sociolla.com/hair-mask/14833-repai...,2022-10-27T07:33:19.380Z,Hair Mask,Hair Care; Hair Treatment; Hair Mask,is_star_effectiveness;is_star_packaging;is_sta...,4.750000,5,"""star_effectiveness"": 5; ""star_packaging"": 5; ...",5,1,0,4,58
7634,273_yves-rocher,Hand Cream Olive Petitgrain,36404,20,Rp 109.000,NaN,https://www.sociolla.com/221-hand-and-foot-cre...,NaN,Hand & Foot Cream,Shop By Departments; Home; 12.12 PRICE POINT 50%,is_star_effectiveness;is_star_packaging;is_sta...,4.968750,8,"""star_effectiveness"": 5; ""star_packaging"": 5; ...",8,2,0,6,117
7635,273_yves-rocher,Color Mask,64153,50,Rp 289.000,NaN,https://vn.sociolla.com/kem-t-c/17224-color-mask,2023-09-20T10:38:15.154Z,Hair Mask,Hair Care; Hair Treatment; Hair Mask,is_star_effectiveness;is_star_packaging;is_sta...,4.500000,2,"""star_effectiveness"": 4.5; ""star_packaging"": 4...",2,1,0,1,35

In [19]:
# mengetahui ringkasan data dari dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7636 entries, 0 to 7635
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   brand_name                    7636 non-null   object
 1   product_name                  7636 non-null   object
 2   product_id                    7636 non-null   int64
 3   beauty_point_earned           7636 non-null   int64
 4   price_range                   7636 non-null   object
 5   price_by_combinations         4087 non-null   object
 6   url                           7636 non-null   object
 7   active_date                   5534 non-null   object
 8   default_category              7636 non-null   object
 9   categories                    7632 non-null   object
 10  rating_types_str              7561 non-null   object
 11  average_rating                7636 non-null   float64
 12  total_reviews                 7636 non-null   int64
 13  average_rating_by_types       5790 non-null   object
 14  total_recommended_count       7636 non-null   int64
 15  total_repurchase_maybe_count  7636 non-null   int64
 16  total_repurchase_no_count     7636 non-null   int64
 17  total_repurchase_yes_count    7636 non-null   int64
 18  total_in_wishlist             7636 non-null   int64
dtypes: float64(1), int64(8), object(10)
memory usage: 1.1+ MB

In [20]:
# mengecek missing value
df.isna().sum()

brand_name                         0
product_name                       0
product_id                         0
beauty_point_earned                0
price_range                        0
price_by_combinations           3549
url                                0
active_date                     2102
default_category                   0
categories                         4
rating_types_str                  75
average_rating                     0
total_reviews                      0
average_rating_by_types         1846
total_recommended_count            0
total_repurchase_maybe_count       0
total_repurchase_no_count          0
total_repurchase_yes_count         0
total_in_wishlist                  0
dtype: int64

In [21]:
# cek statiscial summary
df.describe()

,product_id,beauty_point_earned,average_rating,total_reviews,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
count,7636.000000,7636.000000,7636.000000,7636.000000,7636.000000,7636.000000,7636.000000,7636.000000,7636.000000
mean,82903.974725,37.236773,3.517905,198.197617,186.560503,40.603457,15.479963,141.873494,633.016108
std,27257.173650,46.056962,2.000138,852.067365,803.185318,169.473278,79.716058,625.673542,2055.067002
min,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-317.000000
25%,75267.000000,10.000000,3.910714,1.000000,1.000000,0.000000,0.000000,0.000000,28.000000
50%,91856.500000,20.000000,4.576923,9.000000,9.000000,2.000000,0.000000,6.000000,132.000000
75%,101825.500000,50.000000,4.738155,76.000000,71.000000,17.000000,6.000000,52.000000,480.000000
max,109155.000000,610.000000,5.000000,21536.000000,20804.000000,5025.000000,2824.000000,17653.000000,58568.000000

In [22]:
# cek statiscial summary
df['brand_name'].describe()

count          7636
unique          321
top       246_nivea
freq            160
Name: brand_name, dtype: object

In [23]:
# Mengatasi missing value
for column in df.columns:
    if df[column].dtype == 'object':
        df[column].fillna(df[column].mode()[0], inplace=True)
    else:
        df[column].fillna(df[column].mean(), inplace=True)

/tmp/ipython-input-23-3213337050.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mode()[0], inplace=True)
/tmp/ipython-input-23-3213337050.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)

In [24]:
# cek kembali missing value
df.isna().sum()

brand_name                      0
product_name                    0
product_id                      0
beauty_point_earned             0
price_range                     0
price_by_combinations           0
url                             0
active_date                     0
default_category                0
categories                      0
rating_types_str                0
average_rating                  0
total_reviews                   0
average_rating_by_types         0
total_recommended_count         0
total_repurchase_maybe_count    0
total_repurchase_no_count       0
total_repurchase_yes_count      0
total_in_wishlist               0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7636 entries, 0 to 7635
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   brand_name                    7636 non-null   object
 1   product_name                  7636 non-null   object
 2   product_id                    7636 non-null   int64
 3   beauty_point_earned           7636 non-null   int64
 4   price_range                   7636 non-null   object
 5   price_by_combinations         7636 non-null   object
 6   url                           7636 non-null   object
 7   active_date                   7636 non-null   object
 8   default_category              7636 non-null   object
 9   categories                    7636 non-null   object
 10  rating_types_str              7636 non-null   object
 11  average_rating                7636 non-null   float64
 12  total_reviews                 7636 non-null   int64
 13  average_rating_by_types       7636 non-null   object
 14  total_recommended_count       7636 non-null   int64
 15  total_repurchase_maybe_count  7636 non-null   int64
 16  total_repurchase_no_count     7636 non-null   int64
 17  total_repurchase_yes_count    7636 non-null   int64
 18  total_in_wishlist             7636 non-null   int64
dtypes: float64(1), int64(8), object(10)
memory usage: 1.1+ MB

In [25]:
# Mengecek apakah ada duplicate di seluruh kolom
check_duplicate = df.duplicated().sum()

print(f"Jumlah data yang duplikat = {check_duplicate}")

Jumlah data yang duplikat = 0

In [ ]:
# Handling duplicate
df = df.drop_duplicates()

In [ ]:
# Mengecek duplicate setelah di-handle
handle_duplicate = df.duplicated().sum()

print(f"Jumlah data yang duplikat = {handle_duplicate}")

Jumlah data yang duplikat = 0